// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocmcducdkhwvlchrkaxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbWNkdWNka2h3dmxjaHJrYXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTA3MDMsImV4cCI6MjA2NDQyNjcwM30.jTR5XW6gMlNGu3mpf9hDATXG0UDyEdiPIVcJdOVXMvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);